# Generated by Django 3.0 on 2019-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20191211_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(default='2019-12-11 20:08:42', max_length=100),
        ),
    ]
