# Generated by Django 3.0 on 2019-12-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20191211_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='permanent_url',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
