# Generated by Django 3.0 on 2019-12-15 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20191211_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='permanent_url',
            field=models.CharField(blank=True, default='vPyI', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
