# Generated by Django 3.0 on 2019-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_auto_20191216_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='permanent_url',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
