# Generated by Django 3.0 on 2019-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20191216_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
