# Generated by Django 3.0 on 2019-12-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20191221_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
