# Generated by Django 3.0 on 2020-01-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0010_auto_20191221_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='permanent_url',
            field=models.CharField(default=' ', max_length=6),
        ),
    ]
