# Generated by Django 3.0 on 2020-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0011_auto_20200102_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='permanent_url',
            field=models.CharField(default='______', max_length=6),
        ),
    ]
